export const PAYMENT_GATEWAY = [
  // { name: 'stripe', title: 'Stripe' },
  // { name: 'paypal', title: 'Paypal' },
  // { name: 'razorpay', title: 'RazorPay' },
  // { name: 'mollie', title: 'Mollie' },
  // { name: 'paystack', title: 'Paystack' },
  // { name: 'bitpay', title: 'BitPay' },
  // { name: 'coinbase', title: 'Coinbase' },
  { name: 'tomxu', title: 'Tomxu' },
  { name: 'cod', title: 'COD' },
  { name: 'banking', title: 'Banking' },
  { name: 'momo', title: 'Momo' },
  { name: 'vnpay', title: 'Vnpay' },
  { name: 'moca', title: 'Moca' },
];
